'use client';
import {useEffect,useMemo,useState} from 'react'; import * as XLSX from 'xlsx'; import {supabaseBrowser} from '../../../lib/supabase';
type Student={id:string;admission_no:string;name:string;class_name:string;section:string;parent_name:string|null;parent_phone:string|null;area:string|null;hostel_required:boolean;vehicle_required:boolean;vehicle_area:string|null;family_group_id:string|null};
const cols=['admission_no','name','class_name','section','parent_name','parent_phone','area','hostel_required','vehicle_required','vehicle_area'];
export default function Students(){const sb=supabaseBrowser();const [rows,setRows]=useState<Student[]>([]);const [q,setQ]=useState('');const [fileRows,setFileRows]=useState<Record<string,unknown>[]>([]);const [msg,setMsg]=useState('');const [err,setErr]=useState('');
async function load(){const {data,error}=await sb.from('students').select('*').order('admission_no');if(error)setErr(error.message);else setRows(data||[])}useEffect(()=>{load()},[]);const filtered=useMemo(()=>rows.filter(s=>[s.admission_no,s.name,s.class_name,s.parent_phone||'',s.area||''].join(' ').toLowerCase().includes(q.toLowerCase())),[rows,q]);
function downloadTemplate(){const ws=XLSX.utils.json_to_sheet([{admission_no:'AES001',name:'Rahul Kumar',class_name:'VIII',section:'A',parent_name:'Raj Kumar',parent_phone:'9876543210',area:'Laukahi',hostel_required:'No',vehicle_required:'Yes',vehicle_area:'Route A'}],{header:cols});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Students');XLSX.writeFile(wb,'admission-student-template.xlsx')}
function readExcel(f:File){setMsg('');setErr('');const r=new FileReader();r.onload=e=>{const wb=XLSX.read(e.target?.result,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];setFileRows(XLSX.utils.sheet_to_json(ws));};r.readAsArrayBuffer(f)}
async function importRows(){if(!fileRows.length)return;setErr('');setMsg('Importing…');const payload=fileRows.map(r=>({admission_no:String(r.admission_no||'').trim(),name:String(r.name||'').trim(),class_name:String(r.class_name||'').trim(),section:String(r.section||'A').trim(),parent_name:String(r.parent_name||''),parent_phone:String(r.parent_phone||''),area:String(r.area||''),hostel_required:['yes','true','1'].includes(String(r.hostel_required||'').toLowerCase()),vehicle_required:['yes','true','1'].includes(String(r.vehicle_required||'').toLowerCase()),vehicle_area:String(r.vehicle_area||'')})).filter(r=>r.admission_no&&r.name&&r.class_name);const {error}=await sb.from('students').upsert(payload,{onConflict:'admission_no'});if(error){setErr(error.message);setMsg('')}else{setMsg(`${payload.length} student records imported/updated.`);setFileRows([]);load()}}
return <><div className="page-head"><div><h1>Students</h1><p className="muted">Student master register and Excel import/update.</p></div><div className="actions"><button className="btn secondary" onClick={downloadTemplate}>Download Template</button></div></div><div className="toolbar"><input className="input" placeholder="Search admission, student, class, phone…" value={q} onChange={e=>setQ(e.target.value)}/><input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files&&readExcel(e.target.files[0])}/>{fileRows.length>0&&<button className="btn" onClick={importRows}>Import {fileRows.length} Rows</button>}</div>{msg&&<div className="success" style={{marginBottom:16}}>{msg}</div>}{err&&<div className="error" style={{marginBottom:16}}>{err}</div>}{fileRows.length>0&&<section className="card" style={{marginBottom:16}}><strong>Excel preview</strong><p className="muted">Only rows with admission number, name and class will be imported. Existing admission numbers are updated.</p><div className="table-wrap"><table className="table"><thead><tr>{cols.slice(0,7).map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{fileRows.slice(0,5).map((r,i)=><tr key={i}>{cols.slice(0,7).map(c=><td key={c}>{String(r[c]??'')}</td>)}</tr>)}</tbody></table></div></section>}
<section className="table-wrap"><table className="table"><thead><tr><th>Admission</th><th>Name</th><th>Class</th><th>Parent</th><th>Phone</th><th>Area</th><th>Hostel</th><th>Vehicle</th></tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td><strong>{s.admission_no}</strong></td><td>{s.name}</td><td>{s.class_name}-{s.section}</td><td>{s.parent_name}<br/><span className="muted">{s.parent_phone}</span></td><td>{s.parent_phone}</td><td>{s.area}</td><td><span className={'badge '+(s.hostel_required?'green':'')}>{s.hostel_required?'Yes':'No'}</span></td><td><span className={'badge '+(s.vehicle_required?'green':'')}>{s.vehicle_required?(s.vehicle_area||'Yes'):'No'}</span></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No students found.</div>}</section></>}
